# Import libraries

In [155]:
%matplotlib inline

In [157]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import dataset (from kaggle)

In [4]:
spam_df = pd.read_csv("emails.csv")

In [5]:
spam_df.head(15)

text  spam
0   Subject: naturally irresistible your corporate...     1
1   Subject: the stock trading gunslinger  fanny i...     1
2   Subject: unbelievable new homes made easy  im ...     1
3   Subject: 4 color printing special  request add...     1
4   Subject: do not have money , get software cds ...     1
5   Subject: great nnews  hello , welcome to medzo...     1
6   Subject: here ' s a hot play in motion  homela...     1
7   Subject: save your money buy getting this thin...     1
8   Subject: undeliverable : home based business f...     1
9   Subject: save your money buy getting this thin...     1
10  Subject: las vegas high rise boom  las vegas i...     1
11  Subject: save your money buy getting this thin...     1
12  Subject: brighten those teeth  get your  teeth...     1
13  Subject: wall street phenomenon reaps rewards ...     1
14  Subject: fpa notice : ebay misrepresentation o...     1

In [6]:
spam_df.tail()

text  spam
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

In [7]:
spam_df.describe()

spam
count  5728.000000
mean      0.238827
std       0.426404
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

Information on the dataset

In [9]:
spam_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5728 entries, 0 to 5727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    5728 non-null   object
 1   spam    5728 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 89.6+ KB


# Visualize the dataset

In [11]:
# See which message is the most popular ham/spam message
spam_df.groupby('spam').describe()

text                                                               
     count unique                                                top freq
spam                                                                     
0     4360   4327  Subject: * special notification * aurora versi...    2
1     1368   1368  Subject: naturally irresistible your corporate...    1

In [12]:
# Get the length of these messages
spam_df['length'] = spam_df['text'].apply(len)
spam_df.head()

text  spam  length
0  Subject: naturally irresistible your corporate...     1    1484
1  Subject: the stock trading gunslinger  fanny i...     1     598
2  Subject: unbelievable new homes made easy  im ...     1     448
3  Subject: 4 color printing special  request add...     1     500
4  Subject: do not have money , get software cds ...     1     235

In [13]:
spam_df

text  spam  length
0     Subject: naturally irresistible your corporate...     1    1484
1     Subject: the stock trading gunslinger  fanny i...     1     598
2     Subject: unbelievable new homes made easy  im ...     1     448
3     Subject: 4 color printing special  request add...     1     500
4     Subject: do not have money , get software cds ...     1     235
...                                                 ...   ...     ...
5723  Subject: re : research and development charges...     0    1189
5724  Subject: re : receipts from visit  jim ,  than...     0    1167
5725  Subject: re : enron case study update  wow ! a...     0    2131
5726  Subject: re : interest  david ,  please , call...     0    1060
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0    2331

[5728 rows x 3 columns]

In [14]:
spam_df.length.describe()

count     5728.000000
mean      1556.768680
std       2042.649812
min         13.000000
25%        508.750000
50%        979.000000
75%       1894.250000
max      43952.000000
Name: length, dtype: float64

In [15]:
# See the content of the longest message
spam_df[spam_df['length'] == 43952]['text'].iloc[0]

'Subject: from the enron india newsdesk - april 27 th newsclips  fyi news articles from indian press .  - - - - - - - - - - - - - - - - - - - - - - forwarded by sandeep kohli / enron _ development on 04 / 27 / 2001 08 : 24 am - - - - - - - - - - - - - - - - - - - - - - - - - - -  nikita varma  04 / 27 / 2001 07 : 51 am  to : nikita varma / enron _ development @ enron _ development  cc : ( bcc : sandeep kohli / enron _ development )  subject : from the enron india newsdesk - april 27 th newsclips  friday apr 27 2001 , http : / / www . economictimes . com / today / cmo 3 . htm  dpc board empowers md to cancel mseb contract  friday apr 27 2001 , http : / / www . economictimes . com / today / 27 compl 1 . htm  mseb pays rs 134 cr under \' protest \' to dpc  friday , april 27 , 001 , http : / / www . businessstandard . com / today / economy 4 . asp ? menu = 3  enron india md authorised to terminate ppa  friday , april 27 , 2001 , http : / / www . financialexpress . com / fe 20010427 / topl 

In [16]:
# Now, we will vizualize the ham and spam separately

In [17]:
ham = spam_df[spam_df['spam']==0]

In [18]:
ham

text  spam  length
1368  Subject: hello guys ,  i ' m " bugging you " f...     0    1188
1369  Subject: sacramento weather station  fyi  - - ...     0    1997
1370  Subject: from the enron india newsdesk - jan 1...     0    7902
1371  Subject: re : powerisk 2001 - your invitation ...     0    3644
1372  Subject: re : resco database and customer capt...     0    5535
...                                                 ...   ...     ...
5723  Subject: re : research and development charges...     0    1189
5724  Subject: re : receipts from visit  jim ,  than...     0    1167
5725  Subject: re : enron case study update  wow ! a...     0    2131
5726  Subject: re : interest  david ,  please , call...     0    1060
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0    2331

[4360 rows x 3 columns]

In [19]:
spam = spam_df[spam_df['spam']==1]

In [20]:
spam

text  spam  length
0     Subject: naturally irresistible your corporate...     1    1484
1     Subject: the stock trading gunslinger  fanny i...     1     598
2     Subject: unbelievable new homes made easy  im ...     1     448
3     Subject: 4 color printing special  request add...     1     500
4     Subject: do not have money , get software cds ...     1     235
...                                                 ...   ...     ...
1363  Subject: are you ready to get it ?  hello !  v...     1     347
1364  Subject: would you like a $ 250 gas card ?  do...     1     188
1365  Subject: immediate reply needed  dear sir ,  i...     1    3164
1366  Subject: wanna see me get fisted ?  fist  bang...     1     734
1367  Subject: hot stock info : drgv announces anoth...     1    9342

[1368 rows x 3 columns]

In [21]:
# Visualize both frequencies for spam and ham

In [159]:
spam['length'].plot(bins=60, kind='hist')

<Axes: ylabel='Frequency'>

In [161]:
ham['length'].plot(bins=60, kind='hist') 

<Axes: ylabel='Frequency'>

In [24]:
# Now, we will print the pourcentages for spam and ham messages

In [151]:
print( 'Spam percentage =', (len(spam) / len(spam_df) )*100,"%")

Spam percentage = 23.88268156424581 %


In [26]:
print( 'Ham percentage =', (len(ham) / len(spam_df) )*100,"%")

Ham percentage = 76.11731843575419 %


In [27]:
sns.countplot(spam_df['spam'], label = "Count") 

<Axes: ylabel='Frequency'>

# Start training the model

Before officially training the model, we will remove all punctuations

In [30]:
# Import necessary libraries
import string

In [31]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [32]:
# To check that the punctuation is removed, we will make a test

In [33]:
Test = 'I hope to be happy in the future, Mr. Snow!'

In [34]:
Test_punc_removed = [char for char in Test if char not in string.punctuation]
Test_punc_removed

['I',
 ' ',
 'h',
 'o',
 'p',
 'e',
 ' ',
 't',
 'o',
 ' ',
 'b',
 'e',
 ' ',
 'h',
 'a',
 'p',
 'p',
 'y',
 ' ',
 'i',
 'n',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'f',
 'u',
 't',
 'u',
 'r',
 'e',
 ' ',
 'M',
 'r',
 ' ',
 'S',
 'n',
 'o',
 'w']

In [35]:
# Join the characters again to form the string.
Test_punc_removed_joined = ''.join(Test_punc_removed)
Test_punc_removed_joined

'I hope to be happy in the future Mr Snow'

# Remove Stopwords

In [37]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [38]:
Test_punc_removed_joined

'I hope to be happy in the future Mr Snow'

In [39]:
Test_punc_removed_join_clean = [word for word in Test_punc_removed_joined.split() if word.lower() not in stopwords.words('english')]

In [40]:
# Only important (no so common) words are left
Test_punc_removed_join_clean 

['hope', 'happy', 'future', 'Mr', 'Snow']

# Count vectorizer (example)

In [42]:
# Import library
import sklearn.feature_extraction.text

In [43]:
from sklearn.feature_extraction.text import CountVectorizer
sample_data = ['This is the first document.','This document is the second document.','And this is the third one.','Is this the first document?']

In [44]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(sample_data)

In [45]:
print(vectorizer.get_feature_names_out())

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


In [46]:
print(X.toarray())  

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


# Clean up email messages

In [48]:
# Let's define a pipeline to clean up all the messages 
# The pipeline performs the following: (1) remove punctuation, (2) remove stopwords
# We will first import the necessary libraries

In [49]:
import string
from nltk.corpus import stopwords

In [50]:
def message_cleaning(message):
    Test_punc_removed = [char for char in message if char not in string.punctuation]
    Test_punc_removed_join = ''.join(Test_punc_removed)
    Test_punc_removed_join_clean = [word for word in Test_punc_removed_join.split() if word.lower() not in stopwords.words('english')]
    return Test_punc_removed_join_clean

In [51]:
spam_df_cleaned = spam_df['text'].apply(message_cleaning)

In [52]:
print(spam_df_cleaned[0])

['Subject', 'naturally', 'irresistible', 'corporate', 'identity', 'lt', 'really', 'hard', 'recollect', 'company', 'market', 'full', 'suqgestions', 'information', 'isoverwhelminq', 'good', 'catchy', 'logo', 'stylish', 'statlonery', 'outstanding', 'website', 'make', 'task', 'much', 'easier', 'promise', 'havinq', 'ordered', 'iogo', 'company', 'automaticaily', 'become', 'world', 'ieader', 'isguite', 'ciear', 'without', 'good', 'products', 'effective', 'business', 'organization', 'practicable', 'aim', 'hotat', 'nowadays', 'market', 'promise', 'marketing', 'efforts', 'become', 'much', 'effective', 'list', 'clear', 'benefits', 'creativeness', 'hand', 'made', 'original', 'logos', 'specially', 'done', 'reflect', 'distinctive', 'company', 'image', 'convenience', 'logo', 'stationery', 'provided', 'formats', 'easy', 'use', 'content', 'management', 'system', 'letsyou', 'change', 'website', 'content', 'even', 'structure', 'promptness', 'see', 'logo', 'drafts', 'within', 'three', 'business', 'days', 

In [53]:
print(spam_df['text'][0])

Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : your  mar

# Count Vectorizer to the Emails

In [55]:
import sklearn.feature_extraction.text

In [56]:
from sklearn.feature_extraction.text import CountVectorizer
# Define the cleaning pipeline we defined earlier
vectorizer = CountVectorizer(analyzer = message_cleaning)
spamham_countvectorizer = vectorizer.fit_transform(spam_df['text'])

In [57]:
print(vectorizer.get_feature_names_out())

['\x01' '\x02' '\x03' ... 'zzn' 'zzncacst' 'zzzz']


In [58]:
print(spamham_countvectorizer.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [59]:
# With the shape feature, we can see the number of emails and the number of words which we have extracted from them

In [60]:
spamham_countvectorizer.shape

(5728, 37229)

# Training the Model with all the Dataset

In [62]:
from sklearn.naive_bayes import MultinomialNB

NB_classifier = MultinomialNB()
label = spam_df['spam'].values


In [63]:
NB_classifier.fit(spamham_countvectorizer, label)

MultinomialNB()

In [64]:
testing_sample = ['Money is falling from the sky!!', "Hello Claire, Let me know if you need any further information about the project. Thanks"]
testing_sample_countvectorizer = vectorizer.transform(testing_sample)

In [65]:
test_predict = NB_classifier.predict(testing_sample_countvectorizer)
test_predict

array([1, 0])

In [66]:
# The above array [1, 0] is correct as the first message is spam and the second is ham.

# Divide the Data into Training and Testing

In [68]:
X = spamham_countvectorizer
y = label

In [69]:
X.shape

(5728, 37229)

In [70]:
y.shape

(5728,)

Divide the data so that 80% of it is for training and 20%, for testring

In [72]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [73]:
from sklearn.naive_bayes import MultinomialNB
# Train the model
NB_classifier = MultinomialNB()
NB_classifier.fit(X_train, y_train)

MultinomialNB()

# Evaluation of the Model

In [75]:
from sklearn.metrics import classification_report, confusion_matrix

In [76]:
y_predict_train = NB_classifier.predict(X_train)
y_predict_train
cm = confusion_matrix(y_train, y_predict_train)
sns.heatmap(cm, annot=True)

<Axes: >

In [77]:
# Predicting the Test set results
y_predict_test = NB_classifier.predict(X_test)
cm = confusion_matrix(y_test, y_predict_test)
sns.heatmap(cm, annot=True)

<Axes: >

In [78]:
print(classification_report(y_test, y_predict_test))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00       855
           1       0.98      0.99      0.99       291

    accuracy                           0.99      1146
   macro avg       0.99      0.99      0.99      1146
weighted avg       0.99      0.99      0.99      1146



# Add TF-IDF feature

Tf–idf stands for "Term Frequency–Inverse Document Frequency" is a numerical statistic used to reflect how important a word is to a document in a collection or corpus of documents.

Indeed, if a word appears several times in a given document, this feature will label this word as being meaningful (more important) than other words that appeared fewer times in the same document. However, if a given word appeared several times in a given document but also appeared many times in other documents, there is a probability that this word might be a common frequent word such as 'I', 'am', etc.

TF refers to term frequency which is used to measure the frequency of term occurrence in a document.

IDF refers to inverse document frequency which is used to measure how important a term is.

In [174]:
spamham_countvectorizer

<5728x37229 sparse matrix of type '<class 'numpy.int64'>'
	with 565908 stored elements in Compressed Sparse Row format>

In [176]:
from sklearn.feature_extraction.text import TfidfTransformer

emails_tfidf = TfidfTransformer().fit_transform(spamham_countvectorizer)
print(emails_tfidf.shape)

(5728, 37229)


In [178]:
print(emails_tfidf[:,:])
# Sparse matrix with all the values of IF-IDF

  (0, 358)	0.07062142010984342
  (0, 3638)	0.017223322243491098
  (0, 4230)	0.11082209685254275
  (0, 4364)	0.10148147083118478
  (0, 4775)	0.07526751214796289
  (0, 5786)	0.13540178172468964
  (0, 6311)	0.151063627678959
  (0, 6441)	0.08546123611407894
  (0, 7169)	0.08694550234664027
  (0, 7409)	0.08914721769762693
  (0, 7541)	0.0954821361467869
  (0, 8054)	0.11082209685254275
  (0, 8345)	0.06734823789699165
  (0, 8348)	0.0675146481021124
  (0, 8666)	0.12660366739633563
  (0, 8841)	0.08282883724819641
  (0, 9088)	0.0954589271810286
  (0, 9296)	0.16201763950655423
  (0, 9821)	0.15901754929893994
  (0, 9916)	0.07962097910001154
  (0, 10065)	0.07179540742040964
  (0, 10301)	0.11082209685254275
  (0, 10856)	0.059785791961027845
  (0, 11948)	0.10949657204086065
  (0, 12166)	0.0675146481021124
  :	:
  (5727, 32882)	0.05732511875688421
  (5727, 33116)	0.032573369560353456
  (5727, 33163)	0.033326448909282866
  (5727, 33361)	0.03304411649098978
  (5727, 33770)	0.09511068979631773
  (5727, 338

In [184]:
X = emails_tfidf
y = label

# Split the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Train the model
from sklearn.naive_bayes import MultinomialNB
NB_classifier = MultinomialNB()
NB_classifier.fit(X_train, y_train)

from sklearn.metrics import classification_report, confusion_matrix
y_predict_train = NB_classifier.predict(X_train)
y_predict_train
cm = confusion_matrix(y_train, y_predict_train)
sns.heatmap(cm, annot=True)

<Axes: >

In [182]:
print(classification_report(y_test, y_predict_test))

              precision    recall  f1-score   support

           0       0.76      0.75      0.76       867
           1       0.26      0.28      0.27       279

    accuracy                           0.63      1146
   macro avg       0.51      0.51      0.51      1146
weighted avg       0.64      0.63      0.64      1146

